### ISSUE TITLE
mcl在加载插件到最后的时候闪退出来了

### ISSUE THREAD

**Issue by JialingRichard** [Nambers/Mirai-TuLingBot#1]
把插件直接放上去然后mcl在加载插件到最后的时候闪退出来了，报错信息都没看清。好像有点问题

**Comment by Nambers** [comment]
有配置插件信息吗，就首页说的apikey什么的，可能是这个地方没异常处理就报错了

**Comment by Nambers** [comment]
在cmd中打开mcl看看
