### ISSUE TITLE
机器人启动加载时候提示没有配置文件，但是实际上文件已经存在

### ISSUE THREAD

**Issue by LemonPAKA** [Nambers/Mirai-TuLingBot#2]
2021-05-09 16:21:31 I/TuLingBot: 配置文件目录 "/usr/src/mirai/data/TuLingBot"

2021-05-09 16:21:31 E/TuLingBot: 配置文件不存在(路径:/usr/src/mirai/data/TuLingBot\config.json)，无法正常使用本插件

机器人时间记录时区和我们时区不符，时间上是对的
![image](https://user-images.githubusercontent.com/17202894/117579551-fce98200-b125-11eb-981c-86354781ac0b.png)

**Comment by Nambers** [comment]
可能是没适配linux路径

**Comment by LemonPAKA** [comment]
> 可能是没适配linux路径

插件能创建文件夹，创建不了文件，有没有可能是反斜杠导致的问题

**Comment by Nambers** [comment]
> > 可能是没适配linux路径
> 
> 插件能创建文件夹，创建不了文件，有没有可能是反斜杠导致的问题

我现在手上没linux环境，wsl2升级win10 1909后崩了，你能去试一下吗?
应该没问题
https://wwa.lanzous.com/iclPYozv05a

**Comment by LemonPAKA** [comment]
已修复
