### ISSUE TITLE
如果信息在@bot之前 会导致回复出问题

### ISSUE THREAD

**Issue by Echoosx** [Nambers/Mirai-TuLingBot#4]
简单来说，问题是这个判断导致的：
![image](https://user-images.githubusercontent.com/22994765/144340107-e8dc9b32-07d6-45c5-9b2b-2c4c6a0f1dcc.png)
由于聊天环境中`[mirai:at:bot]`与`message`之间有一个空格，所以如果在聊天环境下@bot之前有内容的话，就会导致`message`与`空格`分两次请求api，并且将两次的回复拼接起来，例如：
<img width="494" alt="Snipaste_2021-12-02_09-28-47" src="https://user-images.githubusercontent.com/22994765/144340984-f64183c3-de8c-47f9-9f48-f201012fe2d7.png">

**Comment by Nambers** [comment]
试一下1.5.0
