### ISSUE TITLE
偶尔会中断运行

### ISSUE THREAD

**Issue by stars-spark** [Nambers/Mirai-TuLingBot#6]
![IMG_20220615_153215.jpg](https://user-images.githubusercontent.com/53867496/173816509-4d4a48f0-53c6-4814-ba5c-f85ab9a4f88c.jpg)![IMG_20220615_114028.jpg](https://user-images.githubusercontent.com/53867496/173816542-d122660c-6a46-4cb8-ad7b-9d0ca45f48c8.jpg)

**Comment by stars-spark** [comment]
然后重启也没有用

**Comment by Nambers** [comment]
那个热加载的警告其他mcl组件发出的，重启mcl后还会出现吗?
然后出现这个empty message报错前这个插件有正常运行吗? 就正常回信息

**Comment by stars-spark** [comment]
> 那个热加载的警告其他mcl组件发出的，重启mcl后还会出现吗?
> 然后出现这个empty message报错前这个插件有正常运行吗? 就正常回信息

报错后可以继续正常回复信息

**Comment by stars-spark** [comment]
只有只发送关键词时，才会有empty message 错误

**Comment by Nambers** [comment]
> 只有只发送关键词时，才会有empty message 错误

发送关键词? 你能不能把debug开一下然后下次遇到这个的时候把debug数据发上来 https://github.com/Nambers/Mirai-TuLingBot#:~:text=%E8%BE%93%E5%87%BAdebug%E4%BF%A1%E6%81%AF-,debug%3A%20false,-%23%20%E5%9B%BE%E7%81%B5

**Comment by Nambers** [comment]
> 只有只发送关键词时，才会有empty message 错误

以及是什么词触发的? 我看看能不能复现

**Comment by stars-spark** [comment]
> 什么

复现的方式很简单，比如在setting.config里设置关键词“小诺”，然后qq只发送小诺的时候，便会出现这样的错误，此时没有回复。下次发送小诺+（内容）仍然可以正常运行。（五天前我跟NoiR反应过这个情况，然后改了这个bug（他改后的文件:链接:https://pan.baidu.com/s/12tw55TMGTpnmjI64F8RBRw 
提取码:13r6）

**Comment by stars-spark** [comment]
> > 只有只发送关键词时，才会有empty message 错误
> 
> 发送关键词? 你能不能把debug开一下然后下次遇到这个的时候把debug数据发上来 https://github.com/Nambers/Mirai-TuLingBot#:~:text=%E8%BE%93%E5%87%BAdebug%E4%BF%A1%E6%81%AF-,debug%3A%20false,-%23%20%E5%9B%BE%E7%81%B5

OK，我看看晚上有没有时间去复现一下

**Comment by Nambers** [comment]
> > 什么
> 
> 复现的方式很简单，比如在setting.config里设置关键词“小诺”，然后qq只发送小诺的时候，便会出现这样的错误，此时没有回复。下次发送小诺+（内容）仍然可以正常运行。（五天前我跟NoiR反应过这个情况，然后改了这个bug（他改后的文件:链接:[https://pan.baidu.com/s/12tw55TMGTpnmjI64F8RBRw ](https://pan.baidu.com/s/12tw55TMGTpnmjI64F8RBRw%C2%A0) 提取码:13r6）

哦那我大概明白了

**Comment by Nambers** [comment]
新版本已发布修复
