### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by stars-spark** [Nambers/Mirai-TuLingBot#7]
免费的图灵机器人可以注册多个，但是一天只能回复一百个问题，我觉得可以加一个功能:一个机器人一天的回复100次后，再切换到另一个已填api，这样回复次数就翻倍了

**Comment by Nambers** [comment]
https://github.com/Nambers/Mirai-TuLingBot/releases/tag/v1.7.0  理论上应该没问题，你使用看看，因为我没有大量使用图灵的环境
