### ISSUE TITLE
能否添加一个回复的时候不要艾特的设置？

### ISSUE THREAD

**Issue by tangcisi** [Nambers/Mirai-TuLingBot#8]
觉得不艾特的回复可能会使聊天过程看起来更加流畅

**Comment by Nambers** [comment]
![image](https://user-images.githubusercontent.com/35139537/174465593-c393d71f-b160-4097-891a-b54a37326721.png)
把关键词删了就行
https://github.com/Nambers/Mirai-TuLingBot#:~:text=%E4%B8%AD%E7%9A%84%E8%A7%A6%E5%8F%91%E5%AD%97%E7%AC%A6%2C-,%E4%B8%BA%E7%A9%BA%E4%BB%A3%E8%A1%A8%E4%BB%BB%E6%84%8F%E6%B6%88%E6%81%AF%E9%83%BD%E4%BC%9A%E8%A7%A6%E5%8F%91,-%5B%E5%8F%AF%E9%80%89%5D
